# DX 601 Week 9 Homework

## Introduction

In this homework, you will practice basic operations with vectors and matrices.

## Example Code

You may find it helpful to refer to this GitHub repository of Jupyter notebooks for example code.

* https://github.com/bu-cds-omds/dx500-examples
* https://github.com/bu-cds-omds/dx601-examples
* https://github.com/bu-cds-omds/dx602-examples

Any calculations demonstrated in code examples or videos may be found in these notebooks, and you are allowed to copy this example code in your homework answers.

## Shared Imports

Do not install or use any additional modules.
Installing additional modules may result in an autograder failure resulting in zero points for some or all problems.

In [120]:
import math
import sys

In [121]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

## Problems

### Problem 1

Set `p1` to the vector from calculating $[0.0, 0.3, 0.65] + [2.2, 6.2, 0.35]$.

In [122]:
# YOUR CHANGES HERE

vector1a = np.asarray([0.0, 0.3, 0.65])
vector1b = np.asarray([2.2, 6.2, 0.35])
p1 = vector1a + vector1b

In [123]:
p1

array([2.2, 6.5, 1. ])

### Problem 2

Set `p2` to the magnitude of the vector $[1, 3, 6]$?

In [124]:
# YOUR CHANGES HERE

vector2 = np.asarray([1, 3, 6])
p2 = np.sqrt(vector2[0]**2 + vector2[1]**2 + vector2[2]**2)

In [125]:
p2

np.float64(6.782329983125268)

### Problem 3

Set `p3` to the magnitude of the vector `q3`.

In [126]:
# DO NOT CHANGE

q3 = np.asarray([5.2, 5.9, 9.1, 4.3, 2.9])
q3

array([5.2, 5.9, 9.1, 4.3, 2.9])

In [127]:
# YOUR CHANGES HERE

# use np.linalg.norm()
p3 = np.linalg.norm(q3)

In [128]:
p3

np.float64(13.098091464026353)

### Problem 4

Set `p4` to the dot product of $[2, 0, 3]$ and $[0, 4, 1]$.

Hint: this should feel like a really easy case to just do in your head.

In [129]:
# YOUR CHANGES HERE

# use np.dot(vector1, vector2) or '@' to find dot product
vector4a = np.asarray([2, 0, 3])
vector4b = np.asarray([0, 4, 1])
p4 = np.dot(vector4a, vector4b)

In [130]:
p4

np.int64(3)

### Problem 5

Set `p5` to the element-wise product of `u5` and `v5`.

Hint: the default behavior of mathematical operations on NumPy arrays is to calculate on an element-wise basis.

In [131]:
# DO NOT CHANGE

u5 = np.asarray([5, 5, 5])
u5

array([5, 5, 5])

In [132]:
# DO NOT CHANGE

v5 = np.asarray([1, 6, 2])
v5

array([1, 6, 2])

In [133]:
# YOUR CHANGES HERE

# use element-wise multiplication for product of vectors
p5 = u5 * v5

In [134]:
p5

array([ 5, 30, 10])

### Problem 6

Set `p6` to the dot product of `u6` and `v6`.

In [135]:
# DO NOT CHANGE

u6 = np.asarray([2.03, 0.40, 1.35, 9.26, 4.23])
u6

array([2.03, 0.4 , 1.35, 9.26, 4.23])

In [136]:
# DO NOT CHANGE

v6 = np.asarray([1.32, 0.96, 2.35, 1.23, 0.25])
v6

array([1.32, 0.96, 2.35, 1.23, 0.25])

In [137]:
# YOUR CHANGES HERE

# use np.dot(vector1, vector2) or '@' to find dot product
p6 = u6 @ v6 

In [138]:
p6

np.float64(18.683400000000002)

### Problem 7

Set `p7` to the cosine similarity of `u7` and `v7`.

In [139]:
# DO NOT CHANGE

u7 = np.asarray([1, 1, 1, 1])
u7

array([1, 1, 1, 1])

In [140]:
# DO NOT CHANGE

v7 = np.asarray([0, 2, 0, 0])
v7

array([0, 2, 0, 0])

In [141]:
# YOUR CHANGES HERE

# use cosine_similarty([vector1], [vector2])
from sklearn.metrics.pairwise import cosine_similarity
similarity = cosine_similarity([u7], [v7])
print (similarity)
p7 = similarity[0][0]

[[0.5]]


In [142]:
p7

np.float64(0.5)

### Problem 8

Set `p8` to the vector $[x, y]$ corresponding to the polar coordinates $(r, \theta) = (1, 1)$.

In [143]:
# YOUR CHANGES HERE

# use math.cos() and math.sin()
p8 = np.asarray([math.cos(1), math.sin(1)])

In [144]:
p8

array([0.54030231, 0.84147098])

### Problem 9

Set `p9` to the scalar-vector product $3.1 \cdot [1.31, 2.06, 9.56, 1.79]$.

In [145]:
# YOUR CHANGES HERE

vector9 = np.asarray([1.31, 2.06, 9.56, 1.79])
p9 = 3.1 * vector9

In [146]:
p9

array([ 4.061,  6.386, 29.636,  5.549])

### Problem 10

Set `p10` to be a unit vector in the same direction as $[1.31, 2.13, -0.92]$.


In [147]:
# YOUR CHANGES HERE

# v / ||v||
# use np.linalg.norm() to calculatge magnitude
vector10 = np.asarray([1.31, 2.13, -0.92])
magnitude_v10 = np.linalg.norm(vector10)
p10 = vector10 / magnitude_v10

In [148]:
p10

array([ 0.49165501,  0.79940853, -0.34528444])

### Problem 11

Set `p11` to be the first of the following vectors that is orthogonal to $[1, 0, 0]$.

* $[1, 1, 1]$
* $[0.5, 1, 1]$
* $[0, 1, 1]$
* $[1, 0, 1]$

In [149]:
# target vector
vector11 = np.asarray([1, 0, 0])

# list of vectors
vector11a = np.asarray([1, 1, 2])
vector11b = np.asarray([0.5, 1, 1])
vector11c = np.asarray([0, 1, 1])
vector11d = np.asarray([1, 0, 1])

# vectors orthogonal if and only if their dot product = 0
# use '@' to compute dot products
dot_product11a = vector11 @ vector11a
print(dot_product11a)
dot_product11b = vector11 @ vector11b
print(dot_product11b)
dot_product11c = vector11 @ vector11c
print(dot_product11c) # dot product = 0
dot_product11d = vector11 @ vector11d
print(dot_product11d)

p11 = vector11c

1
0.5
0
1


In [150]:
p11

array([0, 1, 1])

### Problem 12

Set `p12` to the first vector in the following list which is linearly dependent on the previous vectors.

* $[0, 1, 1]$
* $[0, 0, 1]$
* $[1, 0, 1]$
* $[1, 1, 1]$

In [151]:
# YOUR CHANGES HERE

# list of vectors
vector12a = np.asarray([0, 1, 1])
vector12b = np.asarray([0, 0, 1])
vector12c = np.asarray([1, 0, 1])
vector12d = np.asarray([1, 1, 1])

# list of previousvectors
vector11a = np.asarray([1, 1, 2])
vector11b = np.asarray([0.5, 1, 1])
vector11c = np.asarray([0, 1, 1])
vector11d = np.asarray([1, 0, 1])

# check for linear dependence
dot_product12a = vector12a @ vector11a
print(dot_product12a)
dot_product12b = vector12b @ vector11b
print(dot_product12b)
dot_product12c = vector12c @ vector11c
print(dot_product12c)
dot_product12d = vector12d @ vector11d
print(dot_product12d)

p12 = vector12d

3
1.0
1
2


In [152]:
p12

array([1, 1, 1])

### Problem 13

Set `p13` to the $3 \times 3$ identity matrix.

In [153]:
# YOUR CHANGES HERE

# use np.eye(N, M) for identity matrix with N rows and M columns
p13 = np.eye(3, 3)

In [154]:
p13

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### Problem 14

Set `p14` to the x intercept of the equation $3y + 5x = 2$.

In [155]:
# YOUR CHANGES HERE

# 3y + 5x = 2
# solve for x: 2 - 3y = 5x, 2/5 - 3/5y = x, x = 2/5
p14 = 0.4

In [156]:
p14

0.4

### Problem 15

Given the dictionary of phrases and vectors in `q15`, set `p15` to the phrase (key) whose vector has the highest cosine similarity with $[0.1, 0.5, 0.2]$.

In [157]:
# DO NOT CHANGE

q15 = {
    "cat": [0.1, 0.6, 0.3],
    "dog": [0.2, 0.5, 0.1],
    "elephant": [-0.3, 0.2, 0.5],
    "giraffe": [-0.4, 0.3, -0.1],
    "lion": [0.1, 0.7, 0.2]
}
q15 = {k: np.asarray(v) for k, v in q15.items()}

q15

{'cat': array([0.1, 0.6, 0.3]),
 'dog': array([0.2, 0.5, 0.1]),
 'elephant': array([-0.3,  0.2,  0.5]),
 'giraffe': array([-0.4,  0.3, -0.1]),
 'lion': array([0.1, 0.7, 0.2])}

In [158]:
# YOUR CHANGES HERE

from sklearn.metrics.pairwise import cosine_similarity

# target vector 
vector15 = np.asarray([0.1, 0.5, 0.2])

# set indices to obtain different values from q15
value = [v for v in q15.values()]
for i in range(5):
    indice = value[i]
    print (indice)
    # use cosine_similarty([vector15], [indice]) to calculate cosine similarities
    similarity_calc = cosine_similarity([vector15], [indice])
    print (similarity_calc)

# get the max value of cosine similarities
# get_max = np.max([similarity_calc])
# print(get_max)

p15 = 'cat'


[0.1 0.6 0.3]
[[0.99600652]]
[0.2 0.5 0.1]
[[0.96666667]]
[-0.3  0.2  0.5]
[[0.50349655]]
[-0.4  0.3 -0.1]
[[0.32225169]]
[0.1 0.7 0.2]
[[0.99380799]]


In [159]:
p15

'cat'

### Problem 16

Rescale the vectors $[2, 0, 0, 0]$ and $[0, 1, 1, 1]$ so that they are orthonormal.

Save the first rescaled vector in `p16a` and the second rescaled vector in `p16b`.

In [160]:
# YOUR CHANGES HERE

# define vectors
vector16a = np.asarray([2, 0, 0, 0])
vector16b = np.asarray([0, 1, 1, 1])

# calculate magnitudes (each must have a magnitude of 1)
magnitude16a = np.linalg.norm(vector16a)
print(magnitude16a)
magnitude16b = np.linalg.norm(vector16b)
print(magnitude16b)

# check for orthogonality
dot_product16 = vector16a @ vector16b
print(dot_product16)

# scale vector16a to have magnitude of 1
p16a = 0.5 * vector16a
print (np.linalg.norm(p16a))

2.0
1.7320508075688772
0
1.0


In [161]:
p16a

array([1., 0., 0., 0.])

In [162]:
# YOUR CHANGES HERE

# calculate magnitude (must have magnitude of 1
magnitude16b = np.linalg.norm(vector16b)
print(magnitude16b)

# check for orthogonality
dot_product16 = vector16a @ vector16b
print(dot_product16)

# scale vector16b to have magnitude of 1
p16b = 1/math.sqrt(3) * vector16b
print (np.linalg.norm(p16b))

1.7320508075688772
0
1.0


In [163]:
p16b

array([0.        , 0.57735027, 0.57735027, 0.57735027])

### Problem 17

Set `p17` to the result of the matrix multiplication of `x17` by `y17`.

Hint: NumPy has a function for matrix multiplication, and also overrides the Python @ operator.

In [164]:
# DO NOT CHANGE

x17 = np.array([[0.2, 3.1, 0.6], [-2.9, 2.3, 4.2], [3.0, 4.5, 1.7]])
x17

array([[ 0.2,  3.1,  0.6],
       [-2.9,  2.3,  4.2],
       [ 3. ,  4.5,  1.7]])

In [165]:
# DO NOT CHANGE

y17 = np.array([[1, 2, 3], [6, 5, 4], [7, 8, 9]])
y17

array([[1, 2, 3],
       [6, 5, 4],
       [7, 8, 9]])

In [166]:
# YOUR CHANGES HERE

# use np.matmul() or np.dot() to perform matrix multiplication
p17 = np.matmul(x17, y17)

In [167]:
p17

array([[23. , 20.7, 18.4],
       [40.3, 39.3, 38.3],
       [41.9, 42.1, 42.3]])

### Problem 18

Set `p18` to the angle $\theta$ between the vectors in `u18` and `v18`.
Use the measure of the angle in radians, not degrees.

Hint: you can use the cosine similarity to calculate $\mathrm{cos}~\theta$.
The inverse cosine function to recover the measure of the angle is often called the arc cosine, and both the math and NumPy modules use this for their naming.

In [168]:
# DO NOT CHANGE

u18 = np.asarray([0.3, 0.2, 0.9, -0.4])
u18

array([ 0.3,  0.2,  0.9, -0.4])

In [169]:
# DO NOT CHANGE

v18 = np.asarray([-0.1, 0.3, 0.6, -0.2])
v18

array([-0.1,  0.3,  0.6, -0.2])

In [170]:
# YOUR CHANGES HERE

from sklearn.metrics.pairwise import cosine_similarity

# use cosine_similarty([], []) to calculate cosine
cos_theta = cosine_similarity([u18], [v18])
print (cos_theta)

# use math.acos() to calculate angle in radians
p18 = math.acos(cos_theta[0][0])

[[0.87645982]]


In [171]:
p18

0.5023368499123668

### Problem 19

Set `p19` to be the largest magnitude vector from the following list.

* $[0.1, 0.3, 0.9, -0.8]$
* $[0.2, 0.2, 0.7, 0.6]$
* $[-0.2, 0.2, 0.7, -0.6]$
* $[1.0, 1.0, 0.4, 0.5]$

In [172]:
# YOUR CHANGES HERE

# create vectors
vector19a = np.asarray([0.1, 0.3, 0.9, -0.8])
vector19b = np.asarray([0.2, 0.2, 0.7, 0.6]) 
vector19c = np.asarray([-0.2, 0.2, 0.7, -0.6])      
vector19d = np.asarray([1.0, 1.0, 0.4, 0.5])

# calculate magnitudes of each vector
magnitude19a = np.linalg.norm(vector19a)
print(magnitude19a)
magnitude19b = np.linalg.norm(vector19b)
print(magnitude19b)
magnitude19c = np.linalg.norm(vector19c)
print(magnitude19c)
magnitude19d = np.linalg.norm(vector19d)
print(magnitude19d)

# select vector with largest magnitude
p19 = vector19d

1.2449899597988734
0.9643650760992954
0.9643650760992954
1.5524174696260025


In [173]:
p19

array([1. , 1. , 0.4, 0.5])

### Problem 20

Set `p20` to $3 \mathbf{x} + 5$ where $x$ is stored in `x20`.

In [174]:
# DO NOT CHANGE

x20 = np.asarray([0.2, 0.5, -0.3, 0.8])

In [175]:
# YOUR CHANGES HERE

p20 = 3 * x20 + 5

In [176]:
p20

array([5.6, 6.5, 4.1, 7.4])

### Generative AI Usage

If you used any generative AI tools, please add links to your transcripts below, and any other information that you feel is necessary to comply with the [generative AI policy](https://www.bu.edu/cds-faculty/culture-community/gaia-policy/).
If you did not use any generative AI tools, simply write NONE below.

YOUR ANSWER HERE

In [177]:
# Problem 17: numpy matrix multiplication methods that overrides the '@' operator